---
- name: add input group
  become: yes
  group:
    name=input
    system=yes
    state=present

- name: install udev input rules
  become: yes
  copy:
    src=input.rules
    dest=/etc/udev/rules.d/99-input.rules
    owner=root
    group=root
    mode=0644

- name: install udev permission rules
  become: yes
  copy:
    src=permissions.rules
    dest=/etc/udev/rules.d/10-permissions.rules

- name: create shares group
  become: yes
  group:
    name=shares
    state=present

- name: add kodi user to relevant groups for kodi
  become: yes
  user:
    name=kodi
    state=present
    append=yes
    groups=audio,video,input,dialout,plugdev,tty,shares

- name: set gpu memory to 160 MB for kodi
  become: yes
  lineinfile:
    dest=/boot/config.txt
    regexp="^gpu_mem"
    line="gpu_mem=160"

- name: install kodi
  become: yes
  apt:
    name=kodi
    state=present
    update_cache=yes
    cache_valid_time=3600

- name: install guisettings.xml in order to see a menu
  become: yes
  copy:
    src=guisettings.xml
    dest=/home/kodi/.kodi/userdata/guisettings.xml
    owner=kodi
    group=kodi
    mode=0644
    force=no

- name: disable kodi autostart
  become: yes
  service:
    name=kodi
    enabled=no
  when: ansible_env.IN_CI != 1

- name: enable startup script for kodi
  become: yes
  replace:
    dest=/etc/default/kodi
    regexp=^ENABLED=0
    replace=ENABLED=1

- name: allow kodi user to switch vt
  become: yes
  action: 'copy
    dest="/etc/sudoers.d/kodi-sudoers"
    content="kodi ALL = (root) NOPASSWD: /bin/chvt\n"
    validate="visudo -c -f %s"'
